apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/bawnie01/power-outage-reporting//deployments/kubernetes?ref=d749c62ee0f69a2f0a26e4913a61ac6352ff94bc

images:
  - name: ghcr.io/bawnie01/outage-service
    newTag: sha-d749c62
  - name: ghcr.io/bawnie01/notification-service
    newTag: sha-d749c62
  - name: ghcr.io/bawnie01/sms-partner-mock
    newTag: sha-d749c62

commonLabels:
  app.kubernetes.io/environment: dev
